name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm run build
      - run: npm run ci
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
      - name: Create the docs directory locally in CI
        run: npx typedoc src/index.ts
      - name: Copy badges to docs
        run: cp -r badges docs
      - name: Deploy Documentation 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
